# Generated by Django 3.0.5 on 2020-05-22 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_auto_20200522_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 15, 17, 11, 317149)),
        ),
    ]
